### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by markknol** [kevansevans/HxDoom#5]
Hi, I saw this repo via twitter. Very cool you managed to create Doom in Haxe 💯  Hope you dont mind but wanted to give some random feedback. now I haven't tried to compile the project but just looking at the code I noticed these things.   

1. Instead of doing
```haxe
	public static var WADDATA(get, null):WadCore;

//...

	static function get_WADDATA():WadCore 
	{
		return WADDATA;
	}
```
You can also do:
```haxe
	public static var WADDATA(default, null):WadCore;
```

f you do want to use these kind of getters, I would advice to remove the `public` (to avoid using that getter directly) and add `inline` there, to avoid having the function call, so:
```haxe
	public function get_xpos():Float 
	{
		return xpos;
	}
```
becomes:
```haxe
	inline function get_xpos():Float 
	{
		return xpos;
	}
```
---
Instead of doing:
```haxe
public static inline var 
```
you can do:
```haxe
public static inline final
```
---
Instead of doing: (I saw this in Patch.hx)
```haxe
	public static var CONSTRUCTOR:(Array<Any>) -> Patch = Patch.new;
	
	public var width:Int;
	public var height:Int;
	public var offset_x:Int;
	public var offset_y:Int;
	public var pixels:Vector<Vector<Int>>;
	public function new(_args:Array<Any>) 
```
You can just use
```haxe
	public static var CONSTRUCTOR:(Array<Int>) -> Patch = Patch.new;
	
	public var width:Int;
	public var height:Int;
	public var offset_x:Int;
	public var offset_y:Int;
	public var pixels:Vector<Vector<Int>>;
	public function new(_args:Array<Int>) 
```
- There is no need I guess to use `Any` here, I would avoid this where possible.
- I don't really see a reason why you need `CONSTRUCTOR` instead of just using `Patch.new` directly, or why not even just use `new Patch()`, so you could also remove the CONSTRUCTOR altogether and maybe even drop that array and use something like this

```haxe
// ...
class Patch extends LumpBase
{
	public var width:Int;
	public var height:Int;
	public var offset_x:Int;
	public var offset_y:Int;
	public var pixels:Vector<Vector<Int>>;
	public function new(width,height,offset_x, offset_y) {
		super();
		this.width =  width;
		this.height =  height;
		this.offset_x = offset_x;
		this.offset_y = offset_y;
	}
// ...
```
And at call side:
```haxe
var patch = new Patch(16, 16, 16, 16);
```
Hope it helps in some way 🚀

**Comment by kevansevans** [comment]
`` Hope you dont mind but wanted to give some random feedback.`` No, I don't mind, this is great! Really been needing a fresh set of eyes on this. Let me know if you need help getting it to compile.

***

``I would advice to remove the public (to avoid using that getter directly) and add inline``

I can definitely do this for a lot of them, I have no plans for most of these getters, I just wanted to make sure those specific variables either have an extra step for manipulation or explicitly lock them out from being changed.

***

```
you can do:

public static inline final
```
I'm guessing you mean the ``BYTE_SIZE`` var in the lump classes, what would this change?

***

The CONSTRUCTOR var you see in these classes are part of the dependency injection I want to provide for the user. I want to minimize how much the developer has to change my library in order to apply small fixes or adjustments. This comes from a personal gripe with the leading source ports, where small changes means forking their code and risking being left behind with the latest stable branches. So this approach let's the user quickly redefine new behaviors without having to modify the entire library, an example of which:

```
class CustomSideDef extends SideDef {  
    public function new(_args:Array<Any>) {
        super(_args);
        upper_texture = "BRNBIGC";
        middle_texture = "BRNBIGC";
        lower_texture = "BRNBIGC";
    }
}

...

SideDef.CONSTRUCTOR = CustomSideDef.new;
```
And now all wall/window textures are this grate texture: ![Uploading Screenshot 2020-09-07 10.49.13.png…]()

Easy behavior modifying without having to rework the whole thing to support an inherited class!

I would like to approach this in a way that doesn't require me to use an Any array. I'm probably going to switch back to what you're suggesting and just append an optional Any array at the end of it, as I don't know what the user may need their classes to do. If you have any advice on this, I'd love to hear it!
